name: Merge beta branch
on:
  push:
    branches:
      - beta
jobs:
  merge-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge beta branch
        run: |
          url=$(yq '.modules[-1].sources[0]."x-checker-data".url' org.telegram.desktop.yml)
          version=$(yq '.modules[-1].sources[0].tag' org.telegram.desktop.yml)
          prerelease=$(curl -sSL "$url" | jq --arg version "$version" '.[] | select(.tag_name == $version).prerelease')
          if [ "$prerelease" != false ]; then
            exit
          fi
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout master
          git merge beta
          git push
